export const CLASSES = {
  warrior: {
    id: "warrior",
    name: "Warrior",
    hpGrowth: 6,
    manaGrowth: 1,
    spellDamageBonusPct: 0,
    spellPowerBonus: 0,
    startingStats: { strength: 6, dexterity: 3, vitality: 6, intelligence: 1 },
    startingItems: ["rusty_sword", "leather_armor", "healing_potion"],
    quickSlots: ["power_strike", "guard_break", "healing_potion"],
    abilities: ["power_strike", "guard_break"],
  },
  wizard: {
    id: "wizard",
    name: "Sorceress",
    hpGrowth: 4,
    manaGrowth: 5,
    spellDamageBonusPct: 15,
    spellPowerBonus: 1,
    startingStats: { strength: 1, dexterity: 3, vitality: 3, intelligence: 7 },
    startingItems: ["apprentice_staff", "cloth_robe", "mana_potion", "healing_potion", "magic_missile_tome"],
    quickSlots: ["magic_missile", "arcane_shield", "mana_potion"],
    abilities: ["magic_missile", "arcane_shield"],
  },
};

export const SKILL_TREES = {
  warrior: [
    {
      id: "weapon_mastery",
      name: "Weapon Mastery",
      skills: [
        { id: "warrior_weapon_1", name: "Heavy Swing", description: "+10% melee damage.", effect: { stat: "meleeDamagePct", value: 10 } },
        { id: "warrior_weapon_2", name: "Battle Rhythm", description: "Gain momentum after a kill.", effect: { stat: "killMomentum", value: 2 } },
        { id: "warrior_weapon_3", name: "Crushing Blows", description: "+10% crit chance.", effect: { stat: "critBonus", value: 10 } },
        { id: "warrior_weapon_4", name: "Cleaving Strike", description: "Power Strike deals splash damage.", effect: { stat: "cleave", value: 0.25 } },
        { id: "warrior_weapon_5", name: "Executioner", description: "+25% damage to low-health enemies.", effect: { stat: "executioner", value: 25 } },
      ],
    },
    {
      id: "iron_guard",
      name: "Iron Guard",
      skills: [
        { id: "warrior_guard_1", name: "Toughness", description: "+10 max HP.", effect: { stat: "maxHpFlat", value: 10 } },
        { id: "warrior_guard_2", name: "Armor Training", description: "+2 defense.", effect: { stat: "defenseFlat", value: 2 } },
        { id: "warrior_guard_3", name: "Shielded Stance", description: "Waiting grants guard.", effect: { stat: "waitDefense", value: 2 } },
        { id: "warrior_guard_4", name: "Unyielding", description: "Reduce the first hit on each floor.", effect: { stat: "firstHitReduction", value: 0.5 } },
        { id: "warrior_guard_5", name: "Juggernaut", description: "Gain damage when badly wounded.", effect: { stat: "lowHpDamagePct", value: 15 } },
      ],
    },
    {
      id: "vanguard_tactics",
      name: "Vanguard Tactics",
      skills: [
        { id: "warrior_tactic_1", name: "Combat Footing", description: "+5 accuracy and +10% trap avoidance.", effect: { stat: "accuracyFlat", value: 5 } },
        { id: "warrior_tactic_2", name: "Brace", description: "-25% trap damage.", effect: { stat: "trapReductionPct", value: 25 } },
        { id: "warrior_tactic_3", name: "Charge", description: "Power Strike reaches 2 tiles in a line.", effect: { stat: "chargeRange", value: 2 } },
        { id: "warrior_tactic_4", name: "Disrupting Strike", description: "Melee hits weaken enemies.", effect: { stat: "weakenOnHit", value: 1 } },
        { id: "warrior_tactic_5", name: "Warlord's Advance", description: "Gain +15% damage after moving into melee.", effect: { stat: "advanceDamagePct", value: 15 } },
      ],
    },
  ],
  wizard: [
    {
      id: "elemental_power",
      name: "Elemental Power",
      skills: [
        { id: "wizard_power_1", name: "Empowered Casting", description: "+10% spell damage.", effect: { stat: "spellDamagePct", value: 10 } },
        { id: "wizard_power_2", name: "Focused Arcana", description: "+5 spell accuracy.", effect: { stat: "spellAccuracyFlat", value: 5 } },
        { id: "wizard_power_3", name: "Elemental Surge", description: "First spell in combat deals more damage.", effect: { stat: "firstSpellPct", value: 25 } },
        { id: "wizard_power_4", name: "Arcane Overflow", description: "20% chance for damage spells to cost 0 mana.", effect: { stat: "freeCastChance", value: 0.2 } },
        { id: "wizard_power_5", name: "Master Evocation", description: "Bonus damage to healthy or weak enemies.", effect: { stat: "evocationBonus", value: 20 } },
      ],
    },
    {
      id: "mystic_ward",
      name: "Mystic Ward",
      skills: [
        { id: "wizard_ward_1", name: "Arcane Reserves", description: "+10 max mana.", effect: { stat: "maxManaFlat", value: 10 } },
        { id: "wizard_ward_2", name: "Mana Shielding", description: "Above 50% mana, gain +1 defense.", effect: { stat: "manaShieldDefense", value: 1 } },
        { id: "wizard_ward_3", name: "Steady Mind", description: "Utility spells cost 1 less mana.", effect: { stat: "utilityDiscount", value: 1 } },
        { id: "wizard_ward_4", name: "Reactive Ward", description: "Gain a small barrier after first damage.", effect: { stat: "reactiveWard", value: 6 } },
        { id: "wizard_ward_5", name: "Archmage's Barrier", description: "Emergency damage reduction once per floor.", effect: { stat: "archmageBarrier", value: 0.25 } },
      ],
    },
    {
      id: "control_insight",
      name: "Control and Insight",
      skills: [
        { id: "wizard_control_1", name: "Arcane Sight", description: "Reveal nearby traps sooner.", effect: { stat: "trapSense", value: 2 } },
        { id: "wizard_control_2", name: "Lingering Hex", description: "Control effects last longer.", effect: { stat: "controlDuration", value: 1 } },
        { id: "wizard_control_3", name: "Blink Adept", description: "Blink gains range.", effect: { stat: "blinkRange", value: 1 } },
        { id: "wizard_control_4", name: "Frailty Curse", description: "Control spells expose enemies.", effect: { stat: "frailtyCurse", value: 15 } },
        { id: "wizard_control_5", name: "Battlefield Savant", description: "First utility spell each fight is free.", effect: { stat: "freeUtility", value: 1 } },
      ],
    },
  ],
};

export const SPELLS = {
  power_strike: {
    id: "power_strike",
    name: "Power Strike",
    type: "ability",
    cost: 1,
    range: 1,
    description: "Heavy melee strike with bonus damage.",
  },
  guard_break: {
    id: "guard_break",
    name: "Guard Break",
    type: "ability",
    cost: 2,
    range: 1,
    description: "A crushing melee hit that sunders enemy defense.",
  },
  magic_missile: {
    id: "magic_missile",
    name: "Magic Missile",
    type: "spell",
    cost: 3,
    range: 4,
    damage: [4, 7],
    description: "Reliable ranged spell.",
  },
  arcane_shield: {
    id: "arcane_shield",
    name: "Arcane Shield",
    type: "spell",
    cost: 4,
    range: 0,
    description: "Gain +2 defense for 3 turns.",
  },
  frost_shard: {
    id: "frost_shard",
    name: "Frost Shard",
    type: "spell",
    cost: 4,
    range: 5,
    damage: [6, 9],
    description: "A stronger ranged spell that chills and strikes hard.",
  },
  blink: {
    id: "blink",
    name: "Blink",
    type: "spell",
    cost: 3,
    range: 0,
    description: "Teleport to a safe nearby tile.",
  },
  chain_bolt: {
    id: "chain_bolt",
    name: "Chain Bolt",
    type: "spell",
    cost: 4,
    range: 5,
    damage: [4, 7],
    description: "Lightning arcs to a nearby second target for reduced damage.",
  },
  arcane_pulse: {
    id: "arcane_pulse",
    name: "Arcane Pulse",
    type: "spell",
    cost: 5,
    range: 0,
    damage: [5, 8],
    description: "A close-range burst that strikes all adjacent enemies.",
  },
  ice_shatter: {
    id: "ice_shatter",
    name: "Ice Shatter",
    type: "spell",
    cost: 5,
    range: 5,
    damage: [5, 8],
    description: "Shatters chilled targets for heavy damage and consumes the chill.",
  },
  frailty_hex: {
    id: "frailty_hex",
    name: "Frailty Hex",
    type: "spell",
    cost: 4,
    range: 5,
    damage: [2, 4],
    description: "A weakening curse that leaves enemies hexed and frail.",
  },
  arcane_burst: {
    id: "arcane_burst",
    name: "Arcane Burst",
    type: "spell",
    cost: 6,
    range: 4,
    damage: [8, 12],
    description: "Explosive arcane blast with heavy single-target damage.",
  },
};

export const ITEMS = {
  rusty_sword: { id: "rusty_sword", name: "Rusty Sword", category: "weapon", slot: "weapon", classBias: "warrior", damage: [4, 7], accuracy: 5, value: 14 },
  iron_sword: { id: "iron_sword", name: "Iron Sword", category: "weapon", slot: "weapon", classBias: "warrior", damage: [5, 8], accuracy: 5, rarity: "uncommon", value: 28 },
  militia_sword: { id: "militia_sword", name: "Militia Sword", category: "weapon", slot: "weapon", classBias: "warrior", damage: [4, 6], accuracy: 7, value: 20 },
  woodcutter_axe: { id: "woodcutter_axe", name: "Woodcutter Axe", category: "weapon", slot: "weapon", classBias: "warrior", damage: [5, 7], accuracy: -2, value: 18 },
  raider_axe: { id: "raider_axe", name: "Raider Axe", category: "weapon", slot: "weapon", classBias: "warrior", damage: [5, 8], accuracy: -5, value: 24 },
  legion_spear: { id: "legion_spear", name: "Legion Spear", category: "weapon", slot: "weapon", classBias: "warrior", damage: [6, 9], accuracy: 3, bonus: { defenseFlat: 1 }, rarity: "uncommon", value: 34 },
  butcher_cleaver: { id: "butcher_cleaver", name: "Butcher Cleaver", category: "weapon", slot: "weapon", classBias: "warrior", damage: [7, 10], accuracy: -3, bonus: { meleeDamagePct: 5 }, rarity: "uncommon", value: 40 },
  flame_touched_sword: { id: "flame_touched_sword", name: "Flame-Touched Sword", category: "weapon", slot: "weapon", classBias: "warrior", damage: [6, 9], accuracy: 5, rarity: "rare", value: 56, enchantment: { type: "onHitBonusDamage", value: 2 }, description: "Enchantment: each melee hit deals 2 bonus damage." },
  vampire_axe: { id: "vampire_axe", name: "Vampire Axe", category: "weapon", slot: "weapon", classBias: "warrior", damage: [7, 10], accuracy: -2, rarity: "rare", value: 62, enchantment: { type: "healOnKill", value: 1 }, description: "Enchantment: killing an enemy restores 1 HP." },
  steel_greatsword: { id: "steel_greatsword", name: "Steel Greatsword", category: "weapon", slot: "weapon", classBias: "warrior", damage: [7, 11], accuracy: 3, rarity: "uncommon", value: 48 },
  war_hammer: { id: "war_hammer", name: "War Hammer", category: "weapon", slot: "weapon", classBias: "warrior", damage: [8, 12], accuracy: -3, bonus: { defenseFlat: 1 }, rarity: "uncommon", value: 58 },
  sundering_hammer: { id: "sundering_hammer", name: "Sundering Hammer", category: "weapon", slot: "weapon", classBias: "warrior", damage: [8, 11], accuracy: -2, rarity: "rare", value: 66, bonus: { defenseFlat: 1 }, enchantment: { type: "sunderChance", chance: 0.4, turns: 3, value: 1 }, description: "Enchantment: melee hits have a 40% chance to Sunder the target." },
  sunfire_blade: { id: "sunfire_blade", name: "Sunfire Blade", category: "weapon", slot: "weapon", classBias: "warrior", damage: [9, 13], accuracy: 4, rarity: "boss", value: 96, bonus: { meleeDamagePct: 8 }, enchantment: { type: "onHitBonusDamage", value: 3 }, description: "Enchantment: blazing strikes deal 3 bonus damage and hit harder overall." },
  soulreaver_axe: { id: "soulreaver_axe", name: "Soulreaver Axe", category: "weapon", slot: "weapon", classBias: "warrior", damage: [10, 14], accuracy: -1, rarity: "boss", value: 98, bonus: { maxHpFlat: 8 }, enchantment: { type: "healOnKill", value: 2 }, description: "Enchantment: killing an enemy restores 2 HP." },
  captains_blade: { id: "captains_blade", name: "Captain's Blade", category: "weapon", slot: "weapon", classBias: "warrior", damage: [7, 10], accuracy: 5, rarity: "boss", value: 70 },
  apprentice_staff: { id: "apprentice_staff", name: "Apprentice Staff", category: "weapon", slot: "weapon", classBias: "wizard", damage: [1, 3], magicPower: 1, value: 14 },
  oak_staff: { id: "oak_staff", name: "Oak Staff", category: "weapon", slot: "weapon", classBias: "wizard", damage: [2, 4], magicPower: 2, rarity: "uncommon", value: 28 },
  hedge_wand: { id: "hedge_wand", name: "Hedge Wand", category: "weapon", slot: "weapon", classBias: "wizard", damage: [1, 2], magicPower: 2, accuracy: 3, value: 18 },
  ash_staff: { id: "ash_staff", name: "Ash Staff", category: "weapon", slot: "weapon", classBias: "wizard", damage: [2, 3], magicPower: 2, bonus: { maxManaFlat: 4 }, value: 22 },
  crystal_wand: { id: "crystal_wand", name: "Crystal Wand", category: "weapon", slot: "weapon", classBias: "wizard", damage: [1, 3], magicPower: 3, rarity: "uncommon", value: 34 },
  ember_rod: { id: "ember_rod", name: "Ember Rod", category: "weapon", slot: "weapon", classBias: "wizard", damage: [2, 4], magicPower: 3, bonus: { spellDamagePct: 5 }, rarity: "uncommon", value: 38 },
  moon_staff: { id: "moon_staff", name: "Moon Staff", category: "weapon", slot: "weapon", classBias: "wizard", damage: [2, 5], magicPower: 4, bonus: { maxManaFlat: 6 }, rarity: "uncommon", value: 44 },
  runic_staff: { id: "runic_staff", name: "Runic Staff", category: "weapon", slot: "weapon", classBias: "wizard", damage: [3, 5], magicPower: 4, rarity: "rare", value: 58, enchantment: { type: "spellBonusDamage", value: 2 }, description: "Enchantment: spells deal 2 bonus damage on hit." },
  elder_staff: { id: "elder_staff", name: "Elder Staff", category: "weapon", slot: "weapon", classBias: "wizard", damage: [3, 5], magicPower: 4, rarity: "uncommon", value: 52 },
  sage_wand: { id: "sage_wand", name: "Sage Wand", category: "weapon", slot: "weapon", classBias: "wizard", damage: [2, 4], magicPower: 4, rarity: "rare", value: 64, enchantment: { type: "manaRefundChance", chance: 0.35, value: 2 }, description: "Enchantment: spells have a 35% chance to refund 2 mana after hitting." },
  storm_wand: { id: "storm_wand", name: "Storm Wand", category: "weapon", slot: "weapon", classBias: "wizard", damage: [2, 4], magicPower: 5, bonus: { spellDamagePct: 8 }, rarity: "uncommon", value: 60 },
  voidglass_staff: { id: "voidglass_staff", name: "Voidglass Staff", category: "weapon", slot: "weapon", classBias: "wizard", damage: [4, 6], magicPower: 6, rarity: "boss", value: 96, bonus: { spellDamagePct: 12 }, enchantment: { type: "spellBonusDamage", value: 3 }, description: "Enchantment: spells strike with 3 extra void damage." },
  astral_wand: { id: "astral_wand", name: "Astral Wand", category: "weapon", slot: "weapon", classBias: "wizard", damage: [3, 5], magicPower: 6, rarity: "boss", value: 98, bonus: { spellAccuracyFlat: 6 }, enchantment: { type: "manaRefundChance", chance: 0.45, value: 3 }, description: "Enchantment: precise spell hits often refund 3 mana." },
  ember_staff: { id: "ember_staff", name: "Ember Staff", category: "weapon", slot: "weapon", classBias: "wizard", damage: [2, 4], magicPower: 3, rarity: "boss", bonus: { spellDamagePct: 10 }, value: 72 },
  leather_armor: { id: "leather_armor", name: "Leather Armor", category: "armor", slot: "armor", defense: 2, value: 16 },
  padded_jerkin: { id: "padded_jerkin", name: "Padded Jerkin", category: "armor", slot: "armor", defense: 1, evasion: 1, value: 14 },
  scout_leathers: { id: "scout_leathers", name: "Scout Leathers", category: "armor", slot: "armor", defense: 2, evasion: 2, rarity: "uncommon", value: 24 },
  chain_armor: { id: "chain_armor", name: "Chain Armor", category: "armor", slot: "armor", defense: 3, evasion: -1, rarity: "uncommon", value: 30 },
  iron_cuirass: { id: "iron_cuirass", name: "Iron Cuirass", category: "armor", slot: "armor", defense: 3, rarity: "uncommon", value: 26 },
  bastion_mail: { id: "bastion_mail", name: "Bastion Mail", category: "armor", slot: "armor", defense: 4, bonus: { maxHpFlat: 6 }, rarity: "uncommon", value: 46 },
  guardian_plate: { id: "guardian_plate", name: "Guardian Plate", category: "armor", slot: "armor", defense: 5, bonus: { maxHpFlat: 12 }, rarity: "uncommon", value: 64 },
  emberguard_cuirass: { id: "emberguard_cuirass", name: "Emberguard Cuirass", category: "armor", slot: "armor", classBias: "warrior", defense: 5, bonus: { maxHpFlat: 10, lowHpDamagePct: 10 }, rarity: "rare", value: 74, description: "Enchantment: fortified plates grant +10 max HP and +10% damage while critically wounded." },
  vanguard_warplate: { id: "vanguard_warplate", name: "Vanguard Warplate", category: "armor", slot: "armor", classBias: "warrior", defense: 4, bonus: { meleeDamagePct: 8, waitDefense: 2 }, rarity: "rare", value: 76, description: "Enchantment: gain +8% melee damage, and waiting braces you for +2 defense next turn." },
  abyssal_plate: { id: "abyssal_plate", name: "Abyssal Plate", category: "armor", slot: "armor", defense: 6, bonus: { maxHpFlat: 16, defenseFlat: 1 }, rarity: "boss", value: 94 },
  bulwark_armor: { id: "bulwark_armor", name: "Bulwark Armor", category: "armor", slot: "armor", defense: 4, bonus: { maxHpFlat: 8 }, rarity: "boss", value: 80 },
  cloth_robe: { id: "cloth_robe", name: "Cloth Robe", category: "armor", slot: "armor", defense: 1, value: 16 },
  apprentice_robes: { id: "apprentice_robes", name: "Apprentice Robes", category: "armor", slot: "armor", defense: 1, bonus: { maxManaFlat: 4 }, value: 18 },
  dusk_robe: { id: "dusk_robe", name: "Dusk Robe", category: "armor", slot: "armor", defense: 2, bonus: { maxManaFlat: 8 }, rarity: "uncommon", value: 28 },
  enchanted_robe: { id: "enchanted_robe", name: "Enchanted Robe", category: "armor", slot: "armor", defense: 1, bonus: { maxManaFlat: 5 }, rarity: "uncommon", value: 30 },
  runespun_robe: { id: "runespun_robe", name: "Runespun Robe", category: "armor", slot: "armor", defense: 2, bonus: { maxManaFlat: 10, spellAccuracyFlat: 4 }, rarity: "uncommon", value: 48 },
  archmage_robe: { id: "archmage_robe", name: "Archmage Robe", category: "armor", slot: "armor", defense: 2, bonus: { maxManaFlat: 12, intelligenceFlat: 1 }, rarity: "uncommon", value: 66 },
  spellweave_mantle: { id: "spellweave_mantle", name: "Spellweave Mantle", category: "armor", slot: "armor", classBias: "wizard", defense: 2, bonus: { maxManaFlat: 12, spellDamagePct: 10 }, rarity: "rare", value: 74, description: "Enchantment: woven sigils grant +12 max mana and +10% spell damage." },
  hexwoven_robe: { id: "hexwoven_robe", name: "Hexwoven Robe", category: "armor", slot: "armor", classBias: "wizard", defense: 2, bonus: { spellAccuracyFlat: 5, controlDuration: 1, utilityDiscount: 1 }, rarity: "rare", value: 76, description: "Enchantment: hex-stitched threads sharpen spell aim, extend control effects, and reduce utility spell costs by 1." },
  starweave_robe: { id: "starweave_robe", name: "Starweave Robe", category: "armor", slot: "armor", defense: 3, bonus: { maxManaFlat: 16, intelligenceFlat: 2 }, rarity: "boss", value: 94 },
  robe_of_the_adept: { id: "robe_of_the_adept", name: "Robe of the Adept", category: "armor", slot: "armor", defense: 1, bonus: { maxManaFlat: 10, intelligenceFlat: 1 }, rarity: "boss", value: 80 },
  gauntlets_of_rime: { id: "gauntlets_of_rime", name: "Gauntlets of Rime", category: "hands", slot: "hands", classBias: "warrior", rarity: "uncommon", bonus: { defenseFlat: 1 }, value: 46, handsEffect: { type: "meleeStatusProc", statusId: "chilled", chance: 0.12, turns: 2, value: 1 }, description: "Hands: melee hits have a 12% chance to inflict Chilled for 2 turns." },
  hexward_gloves: { id: "hexward_gloves", name: "Hexward Gloves", category: "hands", slot: "hands", classBias: "wizard", rarity: "uncommon", bonus: { maxHpFlat: 6 }, value: 44, handsEffect: { type: "shortenStatus", statusId: "hexed", amount: 1 }, description: "Hands: incoming Hexed effects last 1 turn less." },
  gravedust_mitts: { id: "gravedust_mitts", name: "Gravedust Mitts", category: "hands", slot: "hands", classBias: "warrior", rarity: "uncommon", bonus: { maxHpFlat: 4 }, value: 44, handsEffect: { type: "meleeStatusProc", statusId: "weakened", chance: 0.1, turns: 2, value: 1 }, description: "Hands: melee hits have a 10% chance to inflict Weakened for 2 turns." },
  runed_handwraps: { id: "runed_handwraps", name: "Runed Handwraps", category: "hands", slot: "hands", classBias: "wizard", rarity: "uncommon", bonus: { maxManaFlat: 6, controlDuration: 1 }, value: 46, description: "Hands: +6 max mana and control effects last 1 turn longer." },
  sundergrip_gauntlets: { id: "sundergrip_gauntlets", name: "Sundergrip Gauntlets", category: "hands", slot: "hands", classBias: "warrior", rarity: "rare", bonus: { defenseFlat: 1 }, value: 60, handsEffect: { type: "meleeStatusProc", statusId: "sundered", chance: 0.15, turns: 3, value: 1 }, description: "Hands: melee hits have a 15% chance to inflict Sundered for 3 turns." },
  spellcatcher_gloves: { id: "spellcatcher_gloves", name: "Spellcatcher Gloves", category: "hands", slot: "hands", classBias: "wizard", rarity: "rare", bonus: { maxManaFlat: 8 }, value: 60, handsEffect: { type: "ignoreSpellStatusChance", chance: 0.25 }, description: "Hands: 25% chance to ignore incoming spell-applied statuses." },
  cinderwraps: { id: "cinderwraps", name: "Cinderwraps", category: "hands", slot: "hands", classBias: "wizard", rarity: "rare", bonus: { magicPowerFlat: 1 }, value: 62, handsEffect: { type: "spellStatusProc", statusId: "weakened", chance: 0.15, turns: 2, value: 1 }, description: "Hands: damage spells have a 15% chance to inflict Weakened for 2 turns." },
  wardens_grips: { id: "wardens_grips", name: "Warden's Grips", category: "hands", slot: "hands", classBias: "warrior", rarity: "rare", bonus: { defenseFlat: 1, maxHpFlat: 6 }, value: 60, handsEffect: { type: "shortenNegativeStatuses", amount: 1 }, description: "Hands: incoming negative statuses last 1 turn less." },
  ring_of_precision: { id: "ring_of_precision", name: "Ring of Precision", category: "accessory", slot: "accessory", rarity: "uncommon", bonus: { accuracyFlat: 5 }, value: 40 },
  ring_of_resolve: { id: "ring_of_resolve", name: "Ring of Resolve", category: "accessory", slot: "accessory", rarity: "uncommon", bonus: { maxHpFlat: 8 }, value: 40 },
  amulet_of_vitality: { id: "amulet_of_vitality", name: "Amulet of Vitality", category: "accessory", slot: "accessory", rarity: "uncommon", bonus: { maxHpFlat: 10 }, value: 42 },
  seal_of_clarity: { id: "seal_of_clarity", name: "Seal of Clarity", category: "accessory", slot: "accessory", rarity: "uncommon", bonus: { maxManaFlat: 8 }, value: 40 },
  charm_of_focus: { id: "charm_of_focus", name: "Charm of Focus", category: "accessory", slot: "accessory", rarity: "uncommon", bonus: { magicPowerFlat: 2 }, value: 42 },
  wardens_loop: { id: "wardens_loop", name: "Warden's Loop", category: "accessory", slot: "accessory", rarity: "uncommon", bonus: { defenseFlat: 1 }, value: 40 },
  spark_charm: { id: "spark_charm", name: "Spark Charm", category: "accessory", slot: "accessory", rarity: "uncommon", bonus: { magicPowerFlat: 1, spellDamagePct: 5 }, value: 44 },
  sigil_of_fortune: { id: "sigil_of_fortune", name: "Sigil of Fortune", category: "accessory", slot: "accessory", rarity: "uncommon", bonus: { accuracyFlat: 3, maxManaFlat: 6, maxHpFlat: 6 }, value: 72 },
  talisman_of_vigor: { id: "talisman_of_vigor", name: "Talisman of Vigor", category: "accessory", slot: "accessory", rarity: "rare", bonus: { maxHpFlat: 12, defenseFlat: 1 }, value: 60 },
  arcseal_pendant: { id: "arcseal_pendant", name: "Arcseal Pendant", category: "accessory", slot: "accessory", rarity: "rare", bonus: { maxManaFlat: 12, magicPowerFlat: 1 }, value: 60 },
  warbrand_token: { id: "warbrand_token", name: "Warbrand Token", category: "accessory", slot: "accessory", rarity: "rare", bonus: { meleeDamagePct: 10, maxHpFlat: 4 }, value: 62 },
  mirror_sigil: { id: "mirror_sigil", name: "Mirror Sigil", category: "accessory", slot: "accessory", rarity: "rare", bonus: { maxHpFlat: 6, maxManaFlat: 6, accuracyFlat: 2 }, value: 62 },
  charm_of_guarding: { id: "charm_of_guarding", name: "Charm of Guarding", category: "accessory", slot: "accessory", rarity: "rare", bonus: { defenseFlat: 2 }, value: 58 },
  chain_of_insight: { id: "chain_of_insight", name: "Chain of Insight", category: "accessory", slot: "accessory", rarity: "rare", bonus: { intelligenceFlat: 1, maxManaFlat: 6 }, value: 60 },
  void_heart: { id: "void_heart", name: "Void Heart", category: "accessory", slot: "accessory", bonus: { maxHpFlat: 10, maxManaFlat: 10, magicPowerFlat: 2, accuracyFlat: 4 }, rarity: "boss", value: 102 },
  healing_potion: { id: "healing_potion", name: "Healing Potion", category: "consumable", effect: { type: "heal", value: 10 }, value: 12 },
  greater_healing_potion: { id: "greater_healing_potion", name: "Greater Healing Potion", category: "consumable", rarity: "uncommon", effect: { type: "heal", value: 18 }, value: 24 },
  mana_potion: { id: "mana_potion", name: "Mana Potion", category: "consumable", effect: { type: "mana", value: 8 }, value: 14 },
  greater_mana_potion: { id: "greater_mana_potion", name: "Greater Mana Potion", category: "consumable", rarity: "uncommon", effect: { type: "mana", value: 14 }, value: 26 },
  scroll_of_escape: { id: "scroll_of_escape", name: "Scroll of Escape", category: "consumable", rarity: "uncommon", effect: { type: "escape" }, value: 28 },
  crypt_vault_key: { id: "crypt_vault_key", name: "Crypt Vault Key", category: "quest", description: "Opens the hidden vault somewhere in Floors 1-9.", value: 0 },
  sunken_vault_key: { id: "sunken_vault_key", name: "Sunken Vault Key", category: "quest", description: "Opens the hidden vault somewhere in Floors 11-19.", value: 0 },
  void_vault_key: { id: "void_vault_key", name: "Void Vault Key", category: "quest", description: "Opens the hidden vault somewhere in Floors 21-29.", value: 0 },
  magic_missile_tome: { id: "magic_missile_tome", name: "Tome of Magic Missile", category: "tome", rarity: "uncommon", spellId: "magic_missile", value: 28 },
  arcane_shield_tome: { id: "arcane_shield_tome", name: "Tome of Arcane Shield", category: "tome", rarity: "uncommon", spellId: "arcane_shield", value: 34 },
  frost_shard_tome: { id: "frost_shard_tome", name: "Tome of Frost Shard", category: "tome", rarity: "uncommon", spellId: "frost_shard", value: 46 },
  blink_tome: { id: "blink_tome", name: "Tome of Blink", category: "tome", rarity: "uncommon", spellId: "blink", value: 44 },
  chain_bolt_tome: { id: "chain_bolt_tome", name: "Tome of Chain Bolt", category: "tome", rarity: "uncommon", spellId: "chain_bolt", value: 50 },
  arcane_pulse_tome: { id: "arcane_pulse_tome", name: "Tome of Arcane Pulse", category: "tome", rarity: "uncommon", spellId: "arcane_pulse", value: 52 },
  ice_shatter_tome: { id: "ice_shatter_tome", name: "Tome of Ice Shatter", category: "tome", rarity: "uncommon", spellId: "ice_shatter", value: 54 },
  frailty_hex_tome: { id: "frailty_hex_tome", name: "Tome of Frailty Hex", category: "tome", rarity: "uncommon", spellId: "frailty_hex", value: 52 },
  arcane_burst_tome: { id: "arcane_burst_tome", name: "Tome of Arcane Burst", category: "tome", rarity: "uncommon", spellId: "arcane_burst", value: 58 },
};

export const ENEMIES = {
  rat: { id: "rat", name: "Rat", behavior: "melee", hp: 8, damage: [2, 3], accuracy: 75, defense: 0, xp: 5, gold: [2, 5], glyph: "R" },
  goblin: { id: "goblin", name: "Goblin", behavior: "skirmisher", hp: 12, damage: [2, 4], accuracy: 85, defense: 0, evasion: 3, xp: 8, gold: [4, 8], glyph: "G" },
  slime: { id: "slime", name: "Slime", behavior: "blocker", hp: 16, damage: [2, 3], accuracy: 70, defense: 2, xp: 9, gold: [3, 7], glyph: "S" },
  skeleton: { id: "skeleton", name: "Skeleton", behavior: "melee", hp: 14, damage: [3, 5], accuracy: 80, defense: 1, xp: 12, gold: [5, 9], glyph: "K" },
  cultist: { id: "cultist", name: "Cultist", behavior: "caster", hp: 10, damage: [3, 5], accuracy: 77, defense: 0, xp: 15, gold: [6, 10], glyph: "C", range: 5 },
  orc_brute: { id: "orc_brute", name: "Orc Brute", behavior: "melee", hp: 20, damage: [4, 7], accuracy: 79, defense: 2, xp: 22, gold: [8, 14], glyph: "O" },
  gloomblade: { id: "gloomblade", name: "Gloomblade", behavior: "skirmisher", hp: 16, damage: [4, 6], accuracy: 86, defense: 1, evasion: 4, xp: 24, gold: [8, 13], glyph: "A" },
  dread_slime: { id: "dread_slime", name: "Dread Slime", behavior: "blocker", hp: 23, damage: [4, 5], accuracy: 76, defense: 2, xp: 25, gold: [7, 12], glyph: "D" },
  shaman: { id: "shaman", name: "Orc Shaman", behavior: "caster", hp: 16, damage: [4, 6], accuracy: 77, defense: 1, xp: 28, gold: [10, 16], glyph: "H", range: 6 },
  chort: { id: "chort", name: "Chort", behavior: "melee", hp: 26, damage: [6, 8], accuracy: 82, defense: 2, xp: 34, gold: [12, 18], glyph: "T" },
  infernal_imp: { id: "infernal_imp", name: "Infernal Imp", behavior: "caster", hp: 18, damage: [4, 7], accuracy: 79, defense: 1, xp: 38, gold: [12, 18], glyph: "I", range: 6 },
  void_stalker: { id: "void_stalker", name: "Void Stalker", behavior: "skirmisher", hp: 24, damage: [6, 9], accuracy: 89, defense: 2, evasion: 5, xp: 42, gold: [13, 20], glyph: "V" },
  doom_ogre: { id: "doom_ogre", name: "Doom Ogre", behavior: "blocker", hp: 33, damage: [7, 10], accuracy: 81, defense: 4, xp: 46, gold: [16, 24], glyph: "O" },
  abyssal_overlord: { id: "abyssal_overlord", name: "Abyssal Overlord", behavior: "boss", hp: 118, damage: [9, 14], accuracy: 90, defense: 6, xp: 160, gold: [60, 96], glyph: "M", range: 6 },
  bone_captain: { id: "bone_captain", name: "Super Skeletor", behavior: "boss", hp: 54, damage: [5, 8], accuracy: 85, defense: 3, xp: 60, gold: [25, 40], glyph: "S", range: 5 },
  patches: { id: "patches", name: "Patches", behavior: "boss", hp: 78, damage: [7, 11], accuracy: 84, defense: 4, xp: 96, gold: [40, 60], glyph: "P", range: 1 },
  mimic: { id: "mimic", name: "Mimic", behavior: "melee", hp: 28, damage: [5, 9], accuracy: 86, defense: 3, xp: 35, gold: [18, 30], glyph: "M" },
  angel: { id: "angel", name: "Celestial Guardian", behavior: "caster", hp: 30, damage: [7, 10], accuracy: 88, defense: 3, xp: 48, gold: [15, 22], glyph: "A", range: 5 },
  ice_zombie: { id: "ice_zombie", name: "Ice Zombie", behavior: "melee", hp: 28, damage: [6, 9], accuracy: 80, defense: 4, xp: 44, gold: [13, 20], glyph: "Z" },
  pumpkin_golem: { id: "pumpkin_golem", name: "Pumpkin Golem", behavior: "blocker", hp: 36, damage: [7, 10], accuracy: 78, defense: 5, xp: 50, gold: [14, 22], glyph: "P" },
  cursed_pumpkin: { id: "cursed_pumpkin", name: "Cursed Pumpkin", behavior: "skirmisher", hp: 24, damage: [6, 10], accuracy: 87, defense: 2, evasion: 5, xp: 46, gold: [14, 21], glyph: "P" },
};

export const FLOOR_CONFIGS = {
  1: { width: 32, height: 24, rooms: [6, 7], enemies: [4, 5], traps: [1, 1], vendorChance: 0 },
  2: { width: 34, height: 24, rooms: [6, 7], enemies: [4, 5], traps: [1, 2], vendorChance: 0 },
  3: { width: 36, height: 25, rooms: [7, 8], enemies: [5, 6], traps: [2, 3], vendorChance: 0.15 },
  4: { width: 38, height: 26, rooms: [7, 8], enemies: [5, 6], traps: [2, 4], vendorChance: 0.2 },
  5: { width: 40, height: 28, rooms: [8, 9], enemies: [6, 7], traps: [3, 4], vendorChance: 0.25 },
  6: { width: 42, height: 28, rooms: [8, 9], enemies: [6, 7], traps: [3, 5], vendorChance: 0.25 },
  7: { width: 44, height: 30, rooms: [8, 10], enemies: [6, 7], traps: [3, 4], vendorChance: 0.3, eliteChance: 0.14 },
  8: { width: 46, height: 30, rooms: [8, 10], enemies: [6, 7], traps: [3, 5], vendorChance: 0.3, eliteChance: 0.18 },
  9: { width: 48, height: 31, rooms: [9, 10], enemies: [7, 8], traps: [4, 5], vendorChance: 0.3, eliteChance: 0.22 },
  11: { width: 50, height: 32, rooms: [9, 10], enemies: [7, 8], traps: [4, 6], vendorChance: 0.32, eliteChance: 0.26 },
  12: { width: 50, height: 33, rooms: [9, 11], enemies: [7, 8], traps: [4, 6], vendorChance: 0.32, eliteChance: 0.28 },
  13: { width: 52, height: 34, rooms: [10, 11], enemies: [7, 9], traps: [5, 7], vendorChance: 0.34, eliteChance: 0.3 },
  14: { width: 52, height: 34, rooms: [10, 11], enemies: [8, 9], traps: [5, 7], vendorChance: 0.34, eliteChance: 0.32 },
  15: { width: 54, height: 35, rooms: [10, 12], enemies: [7, 9], traps: [5, 8], vendorChance: 0.35, eliteChance: 0.3 },
  16: { width: 54, height: 36, rooms: [10, 12], enemies: [8, 10], traps: [7, 9], vendorChance: 0.35, eliteChance: 0.4 },
  17: { width: 56, height: 36, rooms: [11, 12], enemies: [9, 10], traps: [7, 10], vendorChance: 0.36, eliteChance: 0.42 },
  18: { width: 56, height: 37, rooms: [11, 12], enemies: [9, 10], traps: [7, 10], vendorChance: 0.36, eliteChance: 0.44 },
  19: { width: 58, height: 38, rooms: [11, 13], enemies: [9, 11], traps: [8, 10], vendorChance: 0.38, eliteChance: 0.46 },
  20: { width: 58, height: 38, rooms: [11, 13], enemies: [10, 11], traps: [8, 11], vendorChance: 0.38, eliteChance: 0.5 },
  21: { width: 60, height: 39, rooms: [11, 13], enemies: [9, 10], traps: [8, 10], vendorChance: 0.42, eliteChance: 0.46 },
  22: { width: 60, height: 39, rooms: [11, 13], enemies: [9, 10], traps: [8, 10], vendorChance: 0.42, eliteChance: 0.48 },
  23: { width: 62, height: 40, rooms: [11, 13], enemies: [9, 11], traps: [8, 11], vendorChance: 0.44, eliteChance: 0.5 },
  24: { width: 62, height: 40, rooms: [12, 13], enemies: [10, 11], traps: [9, 11], vendorChance: 0.44, eliteChance: 0.52 },
  25: { width: 64, height: 41, rooms: [12, 14], enemies: [10, 11], traps: [9, 11], vendorChance: 0.46, eliteChance: 0.54 },
  26: { width: 64, height: 41, rooms: [12, 14], enemies: [10, 12], traps: [9, 11], vendorChance: 0.46, eliteChance: 0.56 },
  27: { width: 66, height: 42, rooms: [12, 14], enemies: [10, 12], traps: [9, 12], vendorChance: 0.48, eliteChance: 0.58 },
  28: { width: 66, height: 42, rooms: [12, 14], enemies: [11, 12], traps: [10, 12], vendorChance: 0.48, eliteChance: 0.6 },
  29: { width: 68, height: 43, rooms: [13, 14], enemies: [11, 12], traps: [10, 12], vendorChance: 0.5, eliteChance: 0.62 },
};

export const FLOOR_ENCOUNTERS = {
  early: [["rat", "rat"], ["goblin"], ["slime"], ["goblin", "rat"]],
  mid: [["skeleton"], ["goblin", "goblin"], ["slime", "rat"], ["skeleton", "goblin"]],
  late: [["cultist", "slime"], ["cultist", "goblin"], ["skeleton", "skeleton"], ["cultist", "skeleton", "goblin"]],
  deep: [["orc_brute"], ["gloomblade", "skeleton"], ["dread_slime", "cultist"], ["shaman", "orc_brute"], ["gloomblade", "gloomblade"], ["shaman", "skeleton", "cultist"]],
  abyssal: [["chort"], ["shaman", "dread_slime"], ["orc_brute", "gloomblade", "shaman"], ["chort", "cultist"], ["dread_slime", "gloomblade", "gloomblade"], ["angel", "ice_zombie"], ["pumpkin_golem", "cursed_pumpkin"], ["ice_zombie", "ice_zombie"], ["angel", "chort"]],
  endgame: [
    ["doom_ogre"],
    ["infernal_imp", "void_stalker"],
    ["doom_ogre", "infernal_imp"],
    ["chort", "void_stalker", "infernal_imp"],
    ["doom_ogre", "void_stalker"],
    ["doom_ogre", "infernal_imp", "infernal_imp"],
    ["chort", "doom_ogre"],
    ["angel", "pumpkin_golem"],
    ["pumpkin_golem", "cursed_pumpkin", "ice_zombie"],
    ["angel", "doom_ogre"],
    ["cursed_pumpkin", "void_stalker", "ice_zombie"],
  ],
};

export const ROOM_ENCOUNTERS = {
  treasure: {
    late: [["cultist", "skeleton"], ["cultist", "goblin"], ["skeleton", "skeleton"]],
    deep: [["orc_brute", "cultist"], ["gloomblade", "skeleton"], ["dread_slime", "cultist"]],
    abyssal: [["chort", "cultist"], ["orc_brute", "gloomblade"], ["dread_slime", "shaman"], ["angel", "ice_zombie"], ["pumpkin_golem", "cursed_pumpkin"]],
    endgame: [["void_stalker", "infernal_imp"], ["doom_ogre", "infernal_imp"], ["chort", "void_stalker"], ["angel", "pumpkin_golem"], ["cursed_pumpkin", "ice_zombie", "angel"]],
  },
  trap: {
    late: [["slime", "cultist"], ["cultist", "goblin", "goblin"], ["skeleton", "cultist"]],
    deep: [["dread_slime", "cultist"], ["orc_brute", "shaman"], ["gloomblade", "gloomblade"]],
    abyssal: [["dread_slime", "shaman"], ["orc_brute", "gloomblade", "shaman"], ["chort", "cultist"], ["ice_zombie", "cursed_pumpkin"], ["angel", "pumpkin_golem"]],
    endgame: [["doom_ogre", "infernal_imp"], ["void_stalker", "void_stalker", "infernal_imp"], ["doom_ogre", "chort"], ["pumpkin_golem", "ice_zombie", "cursed_pumpkin"], ["angel", "doom_ogre"]],
  },
  elite: {
    late: [["skeleton", "cultist", "goblin"], ["skeleton", "skeleton", "cultist"]],
    deep: [["orc_brute", "gloomblade"], ["dread_slime", "shaman"], ["orc_brute", "cultist", "gloomblade"]],
    abyssal: [["chort", "shaman"], ["dread_slime", "gloomblade", "gloomblade"], ["orc_brute", "gloomblade", "shaman"], ["pumpkin_golem", "angel"], ["ice_zombie", "ice_zombie", "cursed_pumpkin"]],
    endgame: [["doom_ogre", "void_stalker"], ["infernal_imp", "infernal_imp", "doom_ogre"], ["chort", "void_stalker", "infernal_imp"], ["angel", "pumpkin_golem", "ice_zombie"], ["doom_ogre", "cursed_pumpkin", "angel"]],
  },
};

export const TRAPS = {
  spikes: { id: "spikes", name: "Spike Trap", damage: [4, 6], glyph: "^" },
  darts: { id: "darts", name: "Poison Dart Trap", damage: [3, 5], glyph: "!", status: "poisoned" },
  fire: { id: "fire", name: "Fire Trap", damage: [5, 8], glyph: "*" },
  curse: { id: "curse", name: "Curse Trap", damage: [2, 4], glyph: "C", status: "hexed" },
  alarm: { id: "alarm", name: "Alarm Trap", damage: [0, 0], glyph: "A", alerts: true },
};

export const STATUS_DEFINITIONS = {
  chilled: { id: "chilled", name: "Chilled", icon: "C", description: "Accuracy is reduced while frost clings to the target." },
  sundered: { id: "sundered", name: "Sundered", icon: "S", description: "Defense is lowered, making incoming hits bite harder." },
  weakened: { id: "weakened", name: "Weakened", icon: "W", description: "Outgoing damage is reduced until the effect fades." },
  hexed: { id: "hexed", name: "Hexed", icon: "H", description: "Defense is cursed downward, leaving the target exposed." },
  poisoned: { id: "poisoned", name: "Poisoned", icon: "P", description: "Lose 1 HP each action until the poison wears off. Waiting helps you recover faster." },
  arcane_shield: { id: "arcane_shield", name: "Arcane Shield", icon: "A", description: "A temporary magical ward grants bonus defense." },
};

export const BOONS = {
  vicious_star: {
    id: "vicious_star",
    name: "Vicious Star",
    description: "A jagged omen burns overhead. Your strikes bite deeper.",
    summary: "+12% critical strike chance.",
  },
  ward_of_ash: {
    id: "ward_of_ash",
    name: "Ward of Ash",
    description: "A grey veil clings to your skin and resists corruption.",
    summary: "60% chance to ignore incoming negative status effects.",
  },
  iron_remnant: {
    id: "iron_remnant",
    name: "Iron Remnant",
    description: "The sage presses a fragment of old armor into your palm.",
    summary: "+2 permanent defense.",
  },
  crimson_hunger: {
    id: "crimson_hunger",
    name: "Crimson Hunger",
    description: "Every fallen foe leaves a little strength behind.",
    summary: "Restore 2 HP whenever you kill an enemy.",
  },
  fortunes_ledger: {
    id: "fortunes_ledger",
    name: "Fortune's Ledger",
    description: "Merchants recognize your mark and open their best packs.",
    summary: "Vendors stock 2 extra items.",
  },
  sages_echo: {
    id: "sages_echo",
    name: "Sage's Echo",
    description: "The third incantation is carried by memory instead of mana.",
    summary: "Every third spell costs 0 mana.",
  },
  stoneblood: {
    id: "stoneblood",
    name: "Stoneblood",
    description: "Your heart slows, hardens, and endures.",
    summary: "+18 maximum HP.",
  },
  deep_wells: {
    id: "deep_wells",
    name: "Deep Wells",
    description: "Arcane reservoirs open in the dark places of your mind.",
    summary: "+14 maximum mana.",
  },
  relentless_step: {
    id: "relentless_step",
    name: "Relentless Step",
    description: "Once each floor, doom hesitates and lets you lurch forward.",
    summary: "The first time each floor you drop below 25% HP, recover 10 HP.",
  },
  grave_insight: {
    id: "grave_insight",
    name: "Grave Insight",
    description: "The dead teach quickly if you survive long enough to listen.",
    summary: "+20% XP from enemies and bosses.",
  },
  treasure_sense: {
    id: "treasure_sense",
    name: "Treasure Sense",
    description: "Hidden seams in chests and vaults reveal an extra prize.",
    summary: "Each treasure chest gains 1 extra reward roll.",
  },
  battle_trance: {
    id: "battle_trance",
    name: "Battle Trance",
    description: "Each kill leaves a pulse of violence in your hands.",
    summary: "After a kill, your next attack or spell gains +2 damage.",
  },
};

export const CHEST_TABLE = {
  common: ["healing_potion", "mana_potion", "militia_sword", "woodcutter_axe", "iron_sword", "oak_staff", "hedge_wand", "ash_staff", "legion_spear", "ember_rod", "padded_jerkin", "leather_armor", "iron_cuirass", "chain_armor", "apprentice_robes", "enchanted_robe", "scout_leathers", "dusk_robe"],
  rare: ["ring_of_precision", "ring_of_resolve", "amulet_of_vitality", "seal_of_clarity", "charm_of_focus", "wardens_loop", "spark_charm", "gauntlets_of_rime", "hexward_gloves", "gravedust_mitts", "runed_handwraps", "greater_healing_potion", "greater_mana_potion", "scroll_of_escape", "arcane_shield_tome", "frost_shard_tome", "chain_bolt_tome", "frailty_hex_tome", "butcher_cleaver", "moon_staff", "bastion_mail", "runespun_robe"],
  deep: ["steel_greatsword", "war_hammer", "flame_touched_sword", "vampire_axe", "sundering_hammer", "elder_staff", "runic_staff", "sage_wand", "storm_wand", "guardian_plate", "archmage_robe", "emberguard_cuirass", "vanguard_warplate", "spellweave_mantle", "hexwoven_robe", "sundergrip_gauntlets", "spellcatcher_gloves", "cinderwraps", "wardens_grips", "sigil_of_fortune", "talisman_of_vigor", "arcseal_pendant", "warbrand_token", "mirror_sigil", "charm_of_guarding", "chain_of_insight", "blink_tome", "arcane_pulse_tome", "ice_shatter_tome", "arcane_burst_tome"],
  endgame: ["sunfire_blade", "soulreaver_axe", "voidglass_staff", "astral_wand", "abyssal_plate", "starweave_robe", "void_heart"],
};

export const BOSS_REWARDS = {
  warrior: ["captains_blade", "bulwark_armor"],
  wizard: ["ember_staff", "robe_of_the_adept"],
  neutral: ["ring_of_precision", "amulet_of_vitality", "charm_of_focus"],
};

export const FINAL_BOSS_REWARDS = {
  warrior: ["sunfire_blade", "soulreaver_axe", "abyssal_plate"],
  wizard: ["voidglass_staff", "astral_wand", "starweave_robe"],
  neutral: ["void_heart", "sigil_of_fortune"],
};

export const FLOOR20_BOSS_REWARDS = {
  warrior: ["flame_touched_sword", "vampire_axe", "sundering_hammer", "emberguard_cuirass", "vanguard_warplate", "sundergrip_gauntlets"],
  wizard: ["runic_staff", "sage_wand", "spellweave_mantle", "hexwoven_robe", "spellcatcher_gloves", "cinderwraps"],
  neutral: ["sigil_of_fortune", "talisman_of_vigor", "arcseal_pendant", "mirror_sigil", "charm_of_guarding", "chain_of_insight"],
};
